#!/bin/csh -f
setenv USER_SOURCE $ANAPAW_WORK/src

alias makelib 'make -C $ANAPAW_SOURCE clean;make -C $ANAPAW_SOURCE;make -C $ANAPAW_SOURCE install'

alias makeana 'make -C $USER_SOURCE clean;make -C $USER_SOURCE'

alias emacs 'emacs -Q -L /home/exp/Analys/users/ss/emacs.d/ -l /home/exp/Analys/users/ss/emacs.d/emacs_setting -nw'

